# models/staging/schema.yml
version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests: [not_null, unique]
      - name: customer_name
        tests: [not_null]

  - name: stg_products
    columns:
      - name: product_id
        tests: [not_null, unique]
      - name: product_name
        tests: [not_null]
      - name: price
        tests: [not_null]

  - name: stg_orders
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
      - name: ordered_at
        tests: [not_null]
      - name: store_id
        tests: [not_null]
      - name: subtotal
        tests: [not_null]
      - name: tax_paid
        tests: [not_null]
      - name: order_total
        tests: [not_null]

  - name: stg_items
    columns:
      - name: order_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_orders')
              field: order_id
      - name: product_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_products')
              field: product_id
      - name: quantity
        tests:
          - not_null
          - accepted_values:
              values: [1]   # aligns with your current dataset
