version: 2
models:
  - name: fct_order_items
    columns:
      - name: order_id
        tests: [not_null]
      - name: product_id
        tests: [not_null]
      - name: line_revenue
        tests: [not_null]
  - name: fct_orders
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: order_total
        tests: [not_null]
  - name: dim_customers
    columns:
      - name: customer_id
        tests: [not_null, unique]
  - name: orders_fact
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: customer_cohort
        tests: [not_null]
  - name: monthly_summary
    columns:
      - name: order_month
        tests: [not_null, unique]
  - name: customer_pareto
    columns:
      - name: customer_id
        tests: [not_null, unique]
