version: 2
sources:
  - name: raw
    schema: main_raw   
    tables:
      - name: customers
        identifier: raw_customers
      - name: orders
        identifier: raw_orders
      - name: products
        identifier: raw_products
      - name: items                
        identifier: raw_items
